module.exports = {
  apps: [{
    name: 'sbf-backend',
    script: './server.js',
    instances: 1,
    exec_mode: 'fork',
    watch: false,
    max_memory_restart: '1G',
    env_production: {
      NODE_ENV: 'production',
      PORT: 5000,
      MONGODB_URI: 'mongodb+srv://khushalprasad242:ddkka2006@cluster0.qxae3.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0',
      CLOUDINARY_API_KEY: '352883956431227',
      CLOUDINARY_API_SECRET: 'XxJwSR6e971WjHvx5QE2C7oXNO0',
      CLOUDINARY_CLOUD_NAME: 'djtrhfqan',
      DELIVERY_CONFIRMATION_EMAIL_PASS: 'ywmxpkbqitvrpdqx',
      DELIVERY_CONFIRMATION_EMAIL_USER: 'sbfdeliveryconfirmation@gmail.com',
      EMAIL_HOST: 'smtp.gmail.com',
      EMAIL_PASS: 'wemunyukcwuwqvvv',
      EMAIL_PORT: '587',
      EMAIL_USER: '2006sbf@gmail.com',
      GOOGLE_CLIENT_ID: '246004709667-1a33cbkt2b2hq2m1foav1b3j4fsvilef.apps.googleusercontent.com',
      JWT_SECRET: '823c316cbd9f12adcd9aae2ed1adee46d6b53ceced41160cd7e4b4e972057502',
      ORDER_CONFIRMATION_EMAIL_PASS: 'pbxtmsnseknrxrnx',
      ORDER_CONFIRMATION_EMAIL_USER: 'sbforderconfirmation@gmail.com',
      RAZORPAY_KEY_ID: 'rzp_live_D9vJLrTA4TaxBf',
      RAZORPAY_KEY_SECRET: 'lZEQbuduY11quBXY0JAkUHnj'
    },
    error_file: '/var/log/sbf/error.log',
    out_file: '/var/log/sbf/out.log',
    time: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    max_restarts: 10,
    restart_delay: 4000,
    wait_ready: true,
    kill_timeout: 3000,
    autorestart: true
  }]
}; 